### ISSUE TITLE
pfsspy.Input.__init__() missing dtime support in master branch

### ISSUE THREAD

**Issue by STBadman** [dstansby/pfsspy#149]
I cloned pfsspy from the github landing page (master branch) and found the dtime keyword appears to be missing from the Input class __init__() function . Seems an older version of it may have propagated into the master branch? No problems in the release versions.

**Comment by dstansby** [comment]
Yes, this is because I'm about to break everything in 0.5.0, to force inputs to be full on sunpy `Map` objects instead of numpy arrays that are assumed to be in Carrington coordinates. This will make plotting better, make validating the input easier (e.g. checking that the latitude bins are spaced in sin(lat)), and generally encourage people to use proper `Map` objects which have proper FITS coordinate system information in them. It also means one can now specify tracing seeds as coordinate aware astropy `SkyCoord` objects, which can be automatically transformed into the frame of the inputted map.

I've put more info here: https://pfsspy.readthedocs.io/en/latest/changes.html (the latest bit of the URL means docs built from the master branch). Would be super interested in any feedback on this though!
