### ISSUE TITLE
Cannot create PFSS models with HMI synoptic maps

### ISSUE THREAD

**Issue by mbobra** [dstansby/pfsspy#211]
I am not sure if this is already an open issue or not -- if so, I'll close the issue. 

I can't seem to create a PFSS model, even after implementing the fixes in the sunpy/sunpy#4053. The model seems to run, but the output is empty. [Here is my code](https://github.com/mbobra/magnetic-field-models/blob/master/hmipfss.ipynb). Apologies if I'm making an obvious error!

**Comment by dstansby** [comment]
I suspect the issue here is that the input synoptic map has some non-finite (NaN) values, which pfsspy is then propagating all the way through the calculation to give NaNs everywhere. What's the result of `np.sum(~np.isifinite(synoptic_map.data))`?

If I'm right, then I think the action to take here is to raise an error if any non-finite values are detected in the input map.

**Comment by mbobra** [comment]
Good catch, there were a bunch of NaNs in the code ([updated](https://github.com/mbobra/magnetic-field-models/blob/master/hmipfss.ipynb)). I replaced them with 0 (just as a test). 

The model now runs, but the results look odd. Do you think it is the 0's or something else?

**Comment by dstansby** [comment]
I suspect it's the zeros, since they artificially introduce discontinuities into the input. I think you need a cleverer way of filling in the missing data, or a data product that doesn't have missing data. From memory there are some HMI series that do some clever interpolation; https://arxiv.org/pdf/1801.04265.pdf suggests that `hmi.synoptic_mr_polfil_720s` might be of help, but I'm not sure if there's a similar data product for the small synoptic maps.

Thanks for checking by filling in the zeros; I'll open an issue to track raising an error if the input has any NaNs.

**Comment by mbobra** [comment]
Hurray! I downsampled the `hmi.synoptic_mr_polfil_720s` data, and I think it more or less worked ([updated code take 2](https://github.com/mbobra/magnetic-field-models/blob/master/hmipfss.ipynb)).

The only thing I'm worried about is that the SkyCoord object for the polarity inversion line object isn't populated correctly. The inversion line is just a dot (code block 18). Does that look like an error?

**Comment by dstansby** [comment]
It looks like the poles of the solution are a bit noisy due to the way the polar field is filled in (which probably isn't a major issue), which means I suspect there are lots of places that have small polarity inversions near the poles. `output.source_surface_pils` is a list, so if you search that for the item that has the longest `len` then I think you should be able to find the main inversion line.

**Comment by dstansby** [comment]
I'm going to close this as solved; feel free to comment here or open another issue if you run into any more issues.
