### ISSUE TITLE
Code of conduct link from README does not work

### ISSUE THREAD

**Issue by sibirrer** [dstansby/pfsspy#239]
### Description

The link to the code of conduct from the readme and from the description of this issue is not working.

This issue is essential as part of my review for JOSS.

**Comment by dstansby** [comment]
This should have been fixed by https://github.com/dstansby/pfsspy/pull/246, where I added a copy of the SunPy code of conduct to this repository to prevent broken link issues.

When I address https://github.com/dstansby/pfsspy/issues/240 I'll also add a code of conduct link in the documentation (currently it is only linked from the README).
