### ISSUE TITLE
Plotting field lines extrapolated from HMI Daily Update Synchronic Frames on full-disk maps

### ISSUE THREAD

**Issue by nklnm** [dstansby/pfsspy#350]
Hello,

I tried to do the extrapolation with the HMI Daily Update Synchronic Frames as input data. I pretty much followed the examples from your website (for HMI Carrington map and GONG example for field line tracing) and the extrapolation seems to be working fine. However, when I try to plot the seeds and field lines on the full-disk AIA and HMI maps, they are obviously not where they should be and there seems to be a shift of some 20-ish degrees in longitude. [Here is the Jupyter notebook that shows this.](https://github.com/nklnm/HMI-extrapolations/blob/main/hmi_daily_synoptic_map_pfss_extrapolation.ipynb) I did "fix" the coordinates in the HMI Daily Synoptic header similar to what I found [here](https://github.com/mbobra/magnetic-field-models/blob/master/hmipfss.ipynb), but there seems to be something more that needs to be done. I suppose it might have to do with how the observer is defined in the HMI Daily Synoptic header. I've noticed that in the HMI Carrington map the observer is not defined, so sunpy puts it to 'earth' and this plotting of the field lines works fine. I tried deleting the observer coordinates (CRLN_OBS, CRLT_OBS, HGLN_OBS) from the Daily Synoptic map so that it would be set to 'earth', but this didn't change the outcome, the shift is still there. Do you maybe have an idea of where this might be coming from or how it can be fixed? Apologies if this was already resolved somewhere, but I couldn't find an example where somebody tried using this particular type of data as an input.

Thanks!

**Comment by dstansby** [comment]
I suspect this is because the date of your synoptic map and AIA map do not line up, so in the time between you tracing the field lines and the AIA map the corona has rotated due to solar rotation. The slightly hacky way to fix this is modify the date of your synoptic map to match the AIA image - hopefully that should help?

I'm going to close this since I don't think there's anything that needs fixing on the pfsspy side. If my suggestion doesn't work and you need more help, I'd recommend asking at https://community.openastronomy.org/c/sunpy/5, where there's a welcoming community of people developing and using various sunpy packages that should be able to help 😄
