### ISSUE TITLE
Adding more info to the 3D PFSS solution

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/pfsspy#353]
Hello, how can I do the following with the attached 3D figure: 
1. Plot 3D mesh representing the Sun? 
2. Show the Earth line-of-sight and the Earth's orbit? 

![image](https://user-images.githubusercontent.com/43330567/183307170-60d63c96-f4d5-4d12-939a-63a484b6f940.png)

**Comment by TrestanSimon** [comment]
> Plot 3D mesh representing the Sun?

IIRC, doing this will be difficult with matplotlib. If you were to plot both a sphere and the PFSS field lines, the sphere will appear in front of all of the field lines despite physically being behind them (or vice versa). This issue has previously been documented [here](https://matplotlib.org/2.2.2/mpl_toolkits/mplot3d/faq.html), and the recommended workaround is to use MayaVi.

**Comment by dstansby** [comment]
I'd recommend looking at https://docs.sunpy.org/projects/sunkit-pyvista/en/latest/ for 3D visualisation, since it's a true 3D renderer. Since I don't think there's anything to be fixed or added on the pfsspy size I'm going to close this PR. If you still have questions about how to do particular things I'd recommend posting on https://community.openastronomy.org/c/sunpy/5 where there is a welcoming and wider community that should be able to help 😄
